# Generated by Django 4.2.17 on 2024-12-07 18:25

from django.db import migrations, models
import django.db.models.deletion
import main.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_profile_location_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('bmw', 'BMW'), ('mercedes benz', 'Mercedes Benz'), ('audi', 'Audi'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land rover', 'Land Rover'), ('bentley', 'Bentley'), ('bugatti', 'Bugatti'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('porsche', 'Porsche')], default=None, max_length=24)),
                ('model', models.CharField(max_length=64)),
                ('vin', models.CharField(max_length=17)),
                ('mileage', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('engine', models.CharField(max_length=24)),
                ('transmisson', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default=None, max_length=24)),
                ('image', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
